baseURL = "https://creatcodebuild.github.io/hugo-blog/"
languageCode = "en-us"
title = "哲の王"
theme = "ananke"

# Enable comments by entering your Disqus shortname
disqusShortname = "disqus_7Ddl6zJO9B"
